name: CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: connect to server and deploy changes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASS }}
          port: 22
          script: |
            cd admin-dashboard/
            git stash                            
            git pull origin main              
            git stash pop  echo "No stashed changes to apply"  

            rm -rf ./build
            rm -rf /var/www/rakhmatulloh.uz
            mkdir /var/www/rakhmatulloh.uz

            npm install --legacy-peer-deps     
            npm run build

            cp -rf ./build/* /var/www/rakhmatulloh.uz

            pm2 start npm --name "rakhmatulloh.uz" -- run start  pm2 restart rakhmatulloh.uz
